version: '3'
services: 
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: liferay-grow
    volumes:
      - liferay-grow-db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: 'always'
  api:
    build: ./packages/backend
    container_name: liferay-grow-api
    environment: 
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: mysql
      TYPEORM_USERNAME: root
      TYPEORM_PASSWORD: root
      TYPEORM_DATABASE: liferay-grow
      TYPEORM_PORT: 3306
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "false"
      TYPEORM_ENTITIES: dist/src/entity/*.js
      TYPEORM_MIGRATIONS: dist/src/migration/*.js
      HTTP_PORT: 3333
      APP_NAME: Liferay Grow
      NODE_ENV: development
      AUTH_MIDDLEWARE_ENABLED: "true"
      GITHUB_CLIENT_ID: ${CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    ports: 
      - '3333:3333'
    depends_on: 
      - mysql
    web:
      build: ./packages/frontend
      container_name: liferay-grow-frontend
      environment: 
        NEXT_PUBLIC_GITHUB_CLIENT_ID: ${CLIENT_ID}
      ports:
        - '3000:3000'
      depends_on: 
        - api
volumes: 
  liferay-grow-db: