version: '3'
services: 
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: liferay-grow
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - liferay-grow-db:/var/lib/mysql
    restart: 'always'
  api:
    build: ./packages/backend
    container_name: liferay-grow-api
    environment: 
      APP_NAME: Liferay Grow
      HTTP_PORT: 3333
      GITHUB_CLIENT_ID: ${CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: mysql
      TYPEORM_USERNAME: root
      TYPEORM_PASSWORD: root
      TYPEORM_DATABASE: liferay-grow
      TYPEORM_PORT: 3306
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "false"
      TYPEORM_ENTITIES: dist/src/entity/*.js
      TYPEORM_MIGRATIONS: dist/src/migration/*.js
      AUTH_MIDDLEWARE_ENABLED: "true"
      VALIDATE_LIFERAY_ORG: "true"
    depends_on: 
      - mysql
  web:
    build: ./packages/frontend
    container_name: liferay-grow-frontend
    depends_on: 
      - api
      - mysql
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      args:
        - DOMAIN_LIST=${DOMAIN_LIST}
    restart: always
    volumes:
      - ./nginx/config/conf.d/prod:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - api
      - mysql
      - web
volumes: 
  liferay-grow-db: