export default [
  {
    address: 'R. dos Arcos, 160 - Poço da Panela, Recife - PE, 52061-180',
    city: 'Recife',
    country: 'Brazil',
    name: 'Poço da Panela',
    state: 'Pernambuco',
    teams: [
      { name: 'DXP - Workflow' },
      { name: 'DXP - App Builder' },
      { name: 'DXP - Forms' },
      { name: 'DXP - Data Engine' },
      { name: 'AC - Cerebro' },
    ],
  },
  {
    address: 'Paseo de la Castellana, 280, 28046 Madrid, Espanha',
    city: 'Madrid',
    country: 'Spain',
    name: 'Madri',
    state: 'Madrid',
    teams: [
      { name: 'DXP - Echo' },
      { name: 'DXP - Lima' },
      { name: 'DXP - Tango' },
      { name: 'DXP - Headless' },
    ],
  },
  {
    address: '1400 Montefino Ave, Diamond Bar, CA 91765, Estados Unidos',
    city: 'Diamond Bar',
    country: 'United States',
    name: 'Diamond Bar',
    state: 'California',
    teams: [{ name: 'AC - Faro' }, { name: 'DXP - User & System Management' }],
  },
  {
    address: 'Budapest, Madarász Viktor utca 47 a-b, 1138 Hungria',
    city: 'Budapeste',
    country: 'Hungary',
    name: 'Hungary',
    state: 'Budapeste',
    teams: [{ name: 'DXP - Staging' }, { name: 'DXP - Application Security' }],
  },
];
