export default [
  { name: 'DXP - Workflow' },
  { name: 'DXP - Solutions' },
  { name: 'DXP - Forms' },
  { name: 'DXP - Data Engine' },
  { name: 'AC - Cerebro' },
  { name: 'DXP - Echo' },
  { name: 'DXP - Lima' },
  { name: 'DXP - Tango' },
  { name: 'DXP - Headless' },
  { name: 'DXP - Frontend Infrastructure' },
  { name: 'AC - Faro' },
  { name: 'DXP - User & System Management' },
  { name: 'DXP - Publications' },
  { name: 'DXP - Upgrades' },
  { name: 'DXP - Core Infrastructure' },
  { name: 'DXP - Search' },
  { name: 'DXP - Staging' },
  { name: 'DXP - Application Security' },
];
